### ISSUE TITLE
[PACKAGE REQUEST] phockup

### ISSUE THREAD

**Issue by maxexcloo** [dmacias72/unRAID-NerdPack#23]
https://github.com/ivandokov/phockup

phockup is a great little utility that allows you to sort images and videos by exif information. Would be great to have to installed to enable an automated photo processing workflow!

**Comment by dmacias72** [comment]
I'll get to this when I have time. I might even use it.

**Comment by maxexcloo** [comment]
Thanks mate! Right now I'm just running it in a VM, it's a pretty awesome little tool!

**Comment by dartmoordunbar** [comment]
Seconded. It is an excellent tool and the only thing I am missing. I too am running from VM at the moment.

**Comment by maxexcloo** [comment]
Just a note that this doesn't require snap to be installed: 

https://github.com/ivandokov/phockup#linux-without-snap

**Comment by dmacias72** [comment]
I get that but if you look at that apt-get it might need that perl package and it needs to be packaged up in a slackware package. Wish you could just install it with pip3

**Comment by dartmoordunbar** [comment]
I manually installed Perl and exiftool and phockup and it works.

**Comment by maxexcloo** [comment]
That's good to know! Would you be able to post steps :)

**Comment by dmacias72** [comment]
Just Google Slackware makepkg tutorial. You can skip the compile and man parts. Also slackware doesn't really use /opt maybe /usr/lib64/phockup? Also besides the slack-desc you'll need a doinst.sh in the install directory with the ln (symlink) commands. Check this repo under source/Nerdpack/install for examples. It's preferred to used txz instead of tgz. The package name needs to follow the slackware package model e.g. phockup-1.5.9-x86_64-1.txz

**Comment by maxexcloo** [comment]
It worked when installing perl, exiftool, python and then downloading the tarball :)
