### ISSUE TITLE
[PACKAGE REQUEST] icloud_photos_downloader

### ISSUE THREAD

**Issue by maxexcloo** [dmacias72/unRAID-NerdPack#25]
https://github.com/ndbroadbent/icloud_photos_downloader

Is a great utility that can be used to automate downloading photos from iCloud. Currently I run it in a VM. Happy to help make this package (and phockup) but might need some pointers on how to get started :)

**Comment by dmacias72** [comment]
Icloudpd has too many dependencies for me to include them all in NerdPack. You can install icloudpd with pip3. You need python3, setuptools, pip and libffi. Then just run pip3 install icloudpd. Just include this command in your go file or use user script plugin. If phockup used this instead of snap it could be installed the same way.

**Comment by maxexcloo** [comment]
Thanks for the info! I can close this then :)
